### ISSUE TITLE
Project State

### ISSUE THREAD

**Issue by TachyonRSA** [BionicFramework/BionicCLI#15]
Just wondering if this project is still being maintained? It looks like a very promising idea, especially building PWA's with Blazor.

**Comment by bmsantos** [comment]
@TachyonRSA, yes, the project is still being maintained. My time has been short due to work and private life. Until the end of January I will not be able to add much effort to it. Helpers wanted. 😄

**Comment by phillsonntag** [comment]
Are there any updates to the state of the project? The last commit was on 17 Oct 2018. @bmsantos
