### ISSUE TITLE
Bionic was unable to find a platform plugin named: electron, same error with capacitor

### ISSUE THREAD

**Issue by fernandoff** [BionicFramework/BionicCLI#16]
Version 1.0.26

**Comment by bmsantos** [comment]
@fernandoff, thanks for opening the issue.
This has been a common issue with Windows users. Can you please make sure that you have nuget.exe available in Windows PATH?

More details in documentation:
https://bionicframework.github.io/Documentation/0_install/#nuget

**Comment by fernandoff** [comment]
Yes that solved, thank you. Nice job by the way. Hope i can help you with something in the future.

**Comment by bmsantos** [comment]
That would be great. Obrigado
