### ISSUE TITLE
Unable to find compiled project or *** has not yet been initialized.

### ISSUE THREAD

**Issue by eyupalemdar** [BionicFramework/BionicCLI#18]
I get this message when i tried to build a platform like: `bionic platform electron build`
I found the exact problem when looked at the source code. Bionic always look at "netstandard2.0" to find build directory and throws error when the project using a different framework version like "netstandard2.1"

**Comment by bmsantos** [comment]
Hi @eyupalemdar!

As far as I know, DotNet SDK previews only seem to work with "netstandard20".
You can verify this by creating a Blazor Web Client project. Notice that, at this moment using latest DotNet 3.1.100 preview SDK, the project template still generates the following in .csproj file:

```xml
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>
```

If you try to change it to 2.1, Blazor deps build will fail (even though the server works). Blazor dependencies only seem to target 2.0 at this point.
