### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by jhancock4d** [BionicFramework/BionicCLI#23]
The cli doesn't appear to run with the final version of blazor wasm.

**Comment by drannex42** [comment]
I've been wondering the same thing myself. With the new wasm version this project could really find it's place and grow.

**Comment by LesmesWasNotHere** [comment]
Me too

**Comment by drannex42** [comment]
If anyone figures out how to get CapacitorJS to work with the new Blazor versions let me know, I don't really care for the 'Ionic' style of file management or the CLI.

**Comment by ChristianWeyer** [comment]
Do you have any official statements here @bmsantos? Thanks!

**Comment by doyleyoung** [comment]
@jhancock4d @drannex42 @LesmesWasNotHere @ChristianWeyer 
This project is no longer actively updated, but I am happy to merge pull requests and add active users to the team.  Unfortunately, my friend @bmsantos passed.  He left the project to me and I don't have time to work on it.

**Comment by drannex42** [comment]
I hope for the best for you, and send my most sincere condolences to you and their family. --t. Macleod Sawyer Founder, DNX Robotics  ---- On Tue, 02 Feb 2021 14:49:20 -0600  notifications@github.com  wrote ----
@jhancock4d @drannex42 @LesmesWasNotHere @ChristianWeyer
This project is no longer actively updated, but I am happy to merge pull requests and add active users to the team.  Unfortunately, my friend @bmsantos passed.  He left the project to me and I don't have time to work on it.

**Comment by sabitertan** [comment]
@doyleyoung Sorry for your loss 🙏 .

**Comment by sabitertan** [comment]
> If anyone figures out how to get CapacitorJS to work with the new Blazor versions let me know, I don't really care for the 'Ionic' style of file management or the CLI.

I am trying to update this project, if @doyleyoung can give permission or update npm packages later, I would like to keep contributing.
In the mean time feel free to check "manual" project here: https://github.com/sabitertan/BlazorCapacitorWasmApp
